# this is the basic workflow to help you get started with actions

name : "Newman Tests"
on: [push , pull_requests]

jobs: 
build:
runs-on: ubuntu-latest
container:
image: postman/newman
steps:
- name: Checkout
uses: actions/checkout@v2

- name: Run API Tests
run: newman run "Restful BookerBVT.postman_collection.json" -e Production.postman_environment.json   # --env-var "password=$PASSWORD" for password
